# "Machine Learning \& Deep Learning Applications in Modern Power Systems"
## Department of Electrical Engineering - PMEC, Berhampur
### Instructor: Dr. Suryalok Dash 

# Day 5: Exercise Notebook
**Task:** Complete the missing code sections marked with `### YOUR CODE HERE ###`.

In [1]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# The Iris dataset involves predicting plant species based on petal and sepal dimensions.
iris = load_iris()

# Task 1: Create a DataFrame 'X' using iris.data and iris.feature_names
X =pd.DataFrame(iris.data, columns=iris.feature_names)

# Task 2: Create a Series 'y' using iris.target
y = pd.Series(iris.target)

# Task 3: Split the data into X_train, X_test, y_train, y_test using a 30% test size and random_state=42
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# Task 4: Initialize a StandardScaler
scaler = StandardScaler()

# Task 5: Fit the scaler on X_train and transform X_train. Transform X_test as well.
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Task 6: Initialize a LogisticRegression model named 'log_reg'
# Hint: Pass max_iter=500 inside LogisticRegression() to ensure it converges
log_reg = LogisticRegression(max_iter=500)

In [3]:
# Task 7: Train the model using the scaled training features and training target
log_reg.fit(X_train_scaled, y_train)

# Task 8: Generate predictions on the scaled test set and save them to a variable 'y_pred'
y_pred =log_reg.predict(X_test_scaled)

# Task 9: Print the unique classes the model was trained on using the .classes_ attribute of your model
print("Classes recognized by model:", log_reg.classes_)

Classes recognized by model: [0 1 2]


In [4]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Task 10: Calculate and print the overall accuracy score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Task 11: Generate and print the confusion matrix
conf_matrix =confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

# Task 12: Generate and print the classification report
class_report =classification_report(y_test, y_pred)
print("Classification Report:\n", class_report)

Accuracy: 1.0
Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [5]:
import numpy as np
import pandas as pd

# We have a new flower with measurements: Sepal Length=5.1, Sepal Width=3.5, Petal Length=1.4, Petal Width=0.2
new_sample = pd.DataFrame([[5.1, 3.5, 1.4, 0.2]],columns=iris.feature_names)

# Task 13: Scale this 'new_sample' using your previously fitted scaler
new_sample_scaled =scaler.transform(new_sample)

# Task 14: Use the .predict_proba() method on your model to see the probability of each class for this new sample
probabilities =log_reg.predict_proba(new_sample_scaled)
print("Prediction Probabilities:", probabilities)

# Task 15: Use the .predict() method to output the final integer class prediction for this sample
final_prediction = log_reg.predict(new_sample_scaled)
print(f"The model predicts class: {final_prediction} ({iris.target_names[final_prediction[0]]})")

Prediction Probabilities: [[9.79272595e-01 2.07270494e-02 3.55981757e-07]]
The model predicts class: [0] (setosa)
